package co.in.techbuild.bookmanager.domain;

// Generated 19 Nov, 2013 9:54:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "AUTHOR", schema = "PUBLIC", catalog = "TEST")
public class Author implements java.io.Serializable {

	private long authorId;
	private String name;
	private Set<BookAuthor> bookAuthors = new HashSet<BookAuthor>(0);

	public Author() {
	}

	public Author(long authorId) {
		this.authorId = authorId;
	}

	public Author(long authorId, String name, Set<BookAuthor> bookAuthors) {
		this.authorId = authorId;
		this.name = name;
		this.bookAuthors = bookAuthors;
	}

	@Id
	@Column(name = "AUTHOR_ID", unique = true, nullable = false)
	public long getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(long authorId) {
		this.authorId = authorId;
	}

	@Column(name = "NAME", length = 1000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "author")
	public Set<BookAuthor> getBookAuthors() {
		return this.bookAuthors;
	}

	public void setBookAuthors(Set<BookAuthor> bookAuthors) {
		this.bookAuthors = bookAuthors;
	}

}
