package co.in.techbuild.bookmanager.domain;

// Generated 19 Nov, 2013 9:54:39 AM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "BOOK", schema = "PUBLIC", catalog = "TEST")
public class Book implements java.io.Serializable {

	private int bookId;
	private Clob comments;
	private String edition;
	private Character hasCover;
	private String isbn;
	private String isbn10;
	private String isbn13;
	private String path;
	private Date pubDate;
	private Integer rating;
	private String series;
	private Double size;
	private String title;
	private String uuid;
	private Set<BookLang> bookLangs = new HashSet<BookLang>(0);
	private Set<BookTag> bookTags = new HashSet<BookTag>(0);
	private Set<BookPublisher> bookPublishers = new HashSet<BookPublisher>(0);
	private Set<BookAuthor> bookAuthors = new HashSet<BookAuthor>(0);

	public Book() {
	}

	public Book(int bookId) {
		this.bookId = bookId;
	}

	public Book(int bookId, Clob comments, String edition, Character hasCover, String isbn, String isbn10, String isbn13, String path,
			Date pubDate, Integer rating, String series, Double size, String title, String uuid, Set<BookLang> bookLangs,
			Set<BookTag> bookTags, Set<BookPublisher> bookPublishers, Set<BookAuthor> bookAuthors) {
		this.bookId = bookId;
		this.comments = comments;
		this.edition = edition;
		this.hasCover = hasCover;
		this.isbn = isbn;
		this.isbn10 = isbn10;
		this.isbn13 = isbn13;
		this.path = path;
		this.pubDate = pubDate;
		this.rating = rating;
		this.series = series;
		this.size = size;
		this.title = title;
		this.uuid = uuid;
		this.bookLangs = bookLangs;
		this.bookTags = bookTags;
		this.bookPublishers = bookPublishers;
		this.bookAuthors = bookAuthors;
	}

	@Id
	@Column(name = "BOOK_ID", unique = true, nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "COMMENTS")
	public Clob getComments() {
		return this.comments;
	}

	public void setComments(Clob comments) {
		this.comments = comments;
	}

	@Column(name = "EDITION", length = 100)
	public String getEdition() {
		return this.edition;
	}

	public void setEdition(String edition) {
		this.edition = edition;
	}

	@Column(name = "HAS_COVER", length = 1)
	public Character getHasCover() {
		return this.hasCover;
	}

	public void setHasCover(Character hasCover) {
		this.hasCover = hasCover;
	}

	@Column(name = "ISBN")
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "ISBN_10", length = 100)
	public String getIsbn10() {
		return this.isbn10;
	}

	public void setIsbn10(String isbn10) {
		this.isbn10 = isbn10;
	}

	@Column(name = "ISBN_13", length = 100)
	public String getIsbn13() {
		return this.isbn13;
	}

	public void setIsbn13(String isbn13) {
		this.isbn13 = isbn13;
	}

	@Column(name = "PATH", length = 2000)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PUB_DATE", length = 8)
	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	@Column(name = "RATING")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Column(name = "SERIES", length = 500)
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "SIZE", precision = 17, scale = 0)
	public Double getSize() {
		return this.size;
	}

	public void setSize(Double size) {
		this.size = size;
	}

	@Column(name = "TITLE", length = 2000)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "UUID", length = 1000)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookLang> getBookLangs() {
		return this.bookLangs;
	}

	public void setBookLangs(Set<BookLang> bookLangs) {
		this.bookLangs = bookLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookTag> getBookTags() {
		return this.bookTags;
	}

	public void setBookTags(Set<BookTag> bookTags) {
		this.bookTags = bookTags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookPublisher> getBookPublishers() {
		return this.bookPublishers;
	}

	public void setBookPublishers(Set<BookPublisher> bookPublishers) {
		this.bookPublishers = bookPublishers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookAuthor> getBookAuthors() {
		return this.bookAuthors;
	}

	public void setBookAuthors(Set<BookAuthor> bookAuthors) {
		this.bookAuthors = bookAuthors;
	}

	@Override
	public String toString() {
		return "Book [bookId=" + bookId + ", comments=" + comments + ", edition=" + edition + ", hasCover=" + hasCover + ", isbn=" + isbn
				+ ", isbn10=" + isbn10 + ", isbn13=" + isbn13 + ", path=" + path + ", pubDate=" + pubDate + ", rating=" + rating
				+ ", series=" + series + ", size=" + size + ", title=" + title + ", uuid=" + uuid + ", bookLangs=" + bookLangs
				+ ", bookTags=" + bookTags + ", bookPublishers=" + bookPublishers + ", bookAuthors=" + bookAuthors + "]";
	}

}
