package co.in.techbuild.bookmanager.domain;

// Generated 19 Nov, 2013 9:54:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "LANGUAGE", schema = "PUBLIC", catalog = "TEST")
public class Language implements java.io.Serializable {

	private int id;
	private String langCode;
	private String langDesc;
	private Set<BookLang> bookLangs = new HashSet<BookLang>(0);

	public Language() {
	}

	public Language(int id) {
		this.id = id;
	}

	public Language(int id, String langCode, String langDesc, Set<BookLang> bookLangs) {
		this.id = id;
		this.langCode = langCode;
		this.langDesc = langDesc;
		this.bookLangs = bookLangs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LANG_CODE", length = 10)
	public String getLangCode() {
		return this.langCode;
	}

	public void setLangCode(String langCode) {
		this.langCode = langCode;
	}

	@Column(name = "LANG_DESC", length = 100)
	public String getLangDesc() {
		return this.langDesc;
	}

	public void setLangDesc(String langDesc) {
		this.langDesc = langDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<BookLang> getBookLangs() {
		return this.bookLangs;
	}

	public void setBookLangs(Set<BookLang> bookLangs) {
		this.bookLangs = bookLangs;
	}

	@Override
	public String toString() {
		return "Language [id=" + id + ", langCode=" + langCode + ", langDesc=" + langDesc + ", bookLangs=" + bookLangs + "]";
	}

}
