package co.in.techbuild.bookmanager.domain;

// Generated 19 Nov, 2013 9:54:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Publisher generated by hbm2java
 */
@Entity
@Table(name = "PUBLISHER", schema = "PUBLIC", catalog = "TEST")
public class Publisher implements java.io.Serializable {

	private int id;
	private String pubName;
	private Set<BookPublisher> bookPublishers = new HashSet<BookPublisher>(0);

	public Publisher() {
	}

	public Publisher(int id) {
		this.id = id;
	}

	public Publisher(int id, String pubName, Set<BookPublisher> bookPublishers) {
		this.id = id;
		this.pubName = pubName;
		this.bookPublishers = bookPublishers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "PUB_NAME", length = 100)
	public String getPubName() {
		return this.pubName;
	}

	public void setPubName(String pubName) {
		this.pubName = pubName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publisher")
	public Set<BookPublisher> getBookPublishers() {
		return this.bookPublishers;
	}

	public void setBookPublishers(Set<BookPublisher> bookPublishers) {
		this.bookPublishers = bookPublishers;
	}

	@Override
	public String toString() {
		return "Publisher [id=" + id + ", pubName=" + pubName + ", bookPublishers=" + bookPublishers + "]";
	}

}
