package co.in.techbuild.bookmanager.domain;

// Generated 19 Nov, 2013 9:54:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "TAG", schema = "PUBLIC", catalog = "TEST")
public class Tag implements java.io.Serializable {

	private int id;
	private String tagName;
	private Set<BookTag> bookTags = new HashSet<BookTag>(0);

	public Tag() {
	}

	public Tag(int id) {
		this.id = id;
	}

	public Tag(int id, String tagName, Set<BookTag> bookTags) {
		this.id = id;
		this.tagName = tagName;
		this.bookTags = bookTags;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TAG_NAME", length = 300)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<BookTag> getBookTags() {
		return this.bookTags;
	}

	public void setBookTags(Set<BookTag> bookTags) {
		this.bookTags = bookTags;
	}

}
